version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: 127.0.0.1:5000/demo-app:${API_VERSION}
    restart: on-failure
    environment:
      - API_VERSION=${API_VERSION}
      - API_PREFIX=${API_PREFIX}
      - API_BASE_URL=https://${HOST}${API_PREFIX}
      - MONGO_HOST=mongo
      - MONGO_DATABASE_NAME=demo
      - MONGO_DATABASE_USERNAME_FILE=/run/secrets/mongo-application-username
      - MONGO_DATABASE_PASSWORD_FILE=/run/secrets/mongo-application-password
    secrets:
      - mongo-application-username
      - mongo-application-password
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    image: 127.0.0.1:5000/demo-mongo:${API_VERSION}
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo-root-username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGO_INITDB_DATABASE=demo
      - MONGO_DATABASE_USERNAME_FILE=/run/secrets/mongo-application-username
      - MONGO_DATABASE_PASSWORD_FILE=/run/secrets/mongo-application-password
    volumes:
      - mongo-data:/data/db
    secrets:
      - mongo-root-username
      - mongo-root-password
      - mongo-application-username
      - mongo-application-password
  reverse-proxy:
    image: traefik:v2.3.2
    restart: on-failure
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefix
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/etc/traefix/certificates
      - ./traefix-settings.yml:/etc/traefix/traefix-settings.yml
volumes:
  mongo-data:
secrets:
  mongo-root-username:
    file: mongodb-credentials/root-username.txt
  mongo-root-password:
    file: mongodb-credentials/root-password.txt
  mongo-application-username:
    file: mongodb-credentials/application-username.txt
  mongo-application-password:
    file: mongodb-credentials/application-password.txt
