version: '3.8'
services:
  app:
    volumes:
      - ./app:/app
    command: /start-reload.sh
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-services.rule=Host(`${HOST}`)
      - traefik.http.routers.web-services.entrypoints=websecure
      - traefik.http.routers.web-services.tls=true
      - traefik.http.routers.web-services.middlewares=web-services-redirection
      - traefik.http.middlewares.web-services-redirection.redirectregex.regex=^https://([^/]+)/?$$
      - traefik.http.middlewares.web-services-redirection.redirectregex.replacement=https://$${1}${API_PREFIX}
