version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: 127.0.0.1:5000/demo-app:${API_VERSION}
    restart: on-failure
    environment:
      - API_VERSION=${API_VERSION}
      - API_PREFIX=${API_PREFIX}
      - API_BASE_URL=https://${HOST}${API_PREFIX}
      - MONGO_MAIN_HOST=mongo
      - MONGO_MAIN_PORT=27017
      - MONGO_MAIN_DATABASE_NAME=demo
      - MONGO_MAIN_DATABASE_USERNAME_FILE=/run/secrets/mongo-application-username
      - MONGO_MAIN_DATABASE_PASSWORD_FILE=/run/secrets/mongo-application-password
      - ALLOWED_ORIGIN=["http://localhost:8080"]
      - AZURE_AD_AUTHORITY=https://login.microsoftonline.com/ee64f829-1cc2-4fb2-996e-2e0fb78f5f29
      - AZURE_AD_AUDIENCE=d665ee86-da44-4d36-8d30-0ad2b5e16bde
      - AZURE_AD_AUDIENCE_SECRET_FILE=/run/secrets/azure-audience-secret
    secrets:
      - mongo-application-username
      - mongo-application-password
      - azure-audience-secret
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    image: 127.0.0.1:5000/demo-mongo:${API_VERSION}
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo-root-username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGO_INITDB_DATABASE=demo
      - MONGO_DATABASE_USERNAME_FILE=/run/secrets/mongo-application-username
      - MONGO_DATABASE_PASSWORD_FILE=/run/secrets/mongo-application-password
    volumes:
      - mongo-data:/data/db
    secrets:
      - mongo-root-username
      - mongo-root-password
      - mongo-application-username
      - mongo-application-password
volumes:
  mongo-data:
secrets:
  mongo-root-username:
    file: mongodb-credentials/root-username.txt
  mongo-root-password:
    file: mongodb-credentials/root-password.txt
  mongo-application-username:
    file: mongodb-credentials/application-username.txt
  mongo-application-password:
    file: mongodb-credentials/application-password.txt
  azure-audience-secret:
    file: azure_audience_secret.txt
networks:
  default:
    external: true
    name: reverse-proxy
