version: '3.8'
services:
  app:
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`${HOST}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
