version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.3.2
    restart: on-failure
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefix
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/etc/traefix/certificates
      - ./traefix-settings.yml:/etc/traefix/traefix-settings.yml
networks:
  default:
    name: reverse-proxy
